// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var bbox, coord_x, coord_y, id, paper, piece, square, x, y, _i, _j;
    paper = Raphael(1, 1, 800, 600);
    for (x = _i = 1; _i <= 10; x = ++_i) {
      for (y = _j = 1; _j <= 10; y = ++_j) {
        square = paper.rect(x * 28, y * 28, 25, 25);
        square.attr({
          fill: "#EDF",
          stroke: "#000"
        });
        square.data("coord", x + "," + y);
        square.click(function(e) {
          console.log(this.data("coord"));
          return console.log(this.id);
        });
      }
    }
    coord_x = 2;
    coord_y = 10;
    id = ((coord_x - 1) * 10) + (coord_y - 1);
    console.log(id);
    square = paper.getById(id);
    console.log(square.data("coord"));
    bbox = square.getBBox();
    x = bbox.x + (bbox.width / 2);
    y = bbox.y + (bbox.height / 2);
    piece = paper.circle(x, y, 8);
    piece.attr({
      fill: "#F33",
      stroke: "#000"
    });
    return piece = paper.circle();
  });

}).call(this);
